spring:
  application:
    name: loc-backend
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

server:
  port: 8080

springdoc:
  api-docs:
    path: /api/docs/openapi.yaml
scalar:
  enabled: true
  path: /api/docs
  url: ${springdoc.api-docs.path}
